package com.max.ai.tools
import com.max.ai.core.agent.*; import kotlinx.serialization.json.*; import javax.inject.Inject
class WhatsAppTool @Inject constructor() : Tool { override val name="send_whatsapp"; override val description="Send WhatsApp message"; override val parameters=buildJsonObject{put("type","object");putJsonObject("properties"){putJsonObject("contactName"){put("type","string")};putJsonObject("message"){put("type","string")}};putJsonArray("required"){add("contactName");add("message")}}; override suspend fun execute(a:Map<String,String>)=ToolResult(true,"WhatsApp: ${a["contactName"]}")}
class CallTool : Tool { override val name="make_call"; override val description="Make phone call"; override val parameters=buildJsonObject{put("type","object");putJsonObject("properties"){putJsonObject("contactName"){put("type","string")}};putJsonArray("required"){add("contactName")}}; override suspend fun execute(a:Map<String,String>)=ToolResult(true,"Calling ${a["contactName"]}")}
class SmsTool : Tool { override val name="send_sms"; override val description="Send SMS"; override val parameters=buildJsonObject{put("type","object");putJsonObject("properties"){putJsonObject("contactName"){put("type","string")};putJsonObject("message"){put("type","string")}};putJsonArray("required"){add("contactName");add("message")}}; override suspend fun execute(a:Map<String,String>)=ToolResult(true,"SMS sent")}
class GmailTool : Tool { override val name="gmail"; override val description="Read/draft/send emails"; override val parameters=buildJsonObject{put("type","object");putJsonObject("properties"){putJsonObject("action"){put("type","string");put("enum",JsonArray(listOf("read","draft","send").map{JsonPrimitive(it)}))};putJsonObject("to"){put("type","string")};putJsonObject("subject"){put("type","string")};putJsonObject("body"){put("type","string")}};putJsonArray("required"){add("action")}}; override suspend fun execute(a:Map<String,String>)=ToolResult(true,"Gmail ${a["action"]}")}
class FlashlightTool : Tool { override val name="flashlight"; override val description="Toggle flashlight"; override val parameters=buildJsonObject{put("type","object");putJsonObject("properties"){putJsonObject("action"){put("type","string");put("enum",JsonArray(listOf("on","off").map{JsonPrimitive(it)}))}};putJsonArray("required"){add("action")}}; override suspend fun execute(a:Map<String,String>)=ToolResult(true,"Flashlight ${a["action"]}")}
class AppLauncherTool : Tool { override val name="open_app"; override val description="Open installed app"; override val parameters=buildJsonObject{put("type","object");putJsonObject("properties"){putJsonObject("appName"){put("type","string")}};putJsonArray("required"){add("appName")}}; override suspend fun execute(a:Map<String,String>)=ToolResult(true,"Opening ${a["appName"]}")}
class DeviceSettingsTool : Tool { override val name="device_setting"; override val description="WiFi,BT,brightness,DND,volume,airplane"; override val parameters=buildJsonObject{put("type","object");putJsonObject("properties"){putJsonObject("setting"){put("type","string");put("enum",JsonArray(listOf("wifi","bluetooth","brightness","dnd","volume","airplane").map{JsonPrimitive(it)}))};putJsonObject("value"){put("type","string")}};putJsonArray("required"){add("setting")}}; override suspend fun execute(a:Map<String,String>)=ToolResult(true,"${a["setting"]} set")}
class SpotifyTool : Tool { override val name="play_spotify"; override val description="Play on Spotify"; override val parameters=buildJsonObject{put("type","object");putJsonObject("properties"){putJsonObject("query"){put("type","string")}};putJsonArray("required"){add("query")}}; override suspend fun execute(a:Map<String,String>)=ToolResult(true,"Spotify: ${a["query"]}")}
class YouTubeTool : Tool { override val name="play_youtube"; override val description="Play on YouTube"; override val parameters=buildJsonObject{put("type","object");putJsonObject("properties"){putJsonObject("query"){put("type","string")}};putJsonArray("required"){add("query")}}; override suspend fun execute(a:Map<String,String>)=ToolResult(true,"YouTube: ${a["query"]}")}
class WallpaperTool : Tool { override val name="set_wallpaper"; override val description="Set AI wallpaper"; override val parameters=buildJsonObject{put("type","object");putJsonObject("properties"){putJsonObject("prompt"){put("type","string")}};putJsonArray("required"){add("prompt")}}; override suspend fun execute(a:Map<String,String>)=ToolResult(true,"Wallpaper set")}
class WebSearchTool : Tool { override val name="web_search"; override val description="Search the web"; override val parameters=buildJsonObject{put("type","object");putJsonObject("properties"){putJsonObject("query"){put("type","string")}};putJsonArray("required"){add("query")}}; override suspend fun execute(a:Map<String,String>)=ToolResult(true,"Search: ${a["query"]}")}
class WeatherTool : Tool { override val name="weather"; override val description="Get weather"; override val parameters=buildJsonObject{put("type","object");putJsonObject("properties"){putJsonObject("city"){put("type","string")}}}; override suspend fun execute(a:Map<String,String>)=ToolResult(true,"Weather: ${a["city"]}")}
class StockTool : Tool { override val name="stock_price"; override val description="Get stock price"; override val parameters=buildJsonObject{put("type","object");putJsonObject("properties"){putJsonObject("symbol"){put("type","string")}};putJsonArray("required"){add("symbol")}}; override suspend fun execute(a:Map<String,String>)=ToolResult(true,"Stock: ${a["symbol"]}")}
class DeepResearchTool : Tool { override val name="deep_research"; override val description="Multi-step deep research"; override val parameters=buildJsonObject{put("type","object");putJsonObject("properties"){putJsonObject("topic"){put("type","string")}};putJsonArray("required"){add("topic")}}; override suspend fun execute(a:Map<String,String>)=ToolResult(true,"Research: ${a["topic"]}")}
class LocationTool : Tool { override val name="location"; override val description="Location/map/directions"; override val parameters=buildJsonObject{put("type","object");putJsonObject("properties"){putJsonObject("action"){put("type","string");put("enum",JsonArray(listOf("current","map","directions").map{JsonPrimitive(it)}))}};putJsonArray("required"){add("action")}}; override suspend fun execute(a:Map<String,String>)=ToolResult(true,"Location: ${a["action"]}")}
class CalendarTool : Tool { override val name="calendar"; override val description="Query/create calendar events"; override val parameters=buildJsonObject{put("type","object");putJsonObject("properties"){putJsonObject("action"){put("type","string");put("enum",JsonArray(listOf("query","create").map{JsonPrimitive(it)}))};putJsonObject("title"){put("type","string")};putJsonObject("date"){put("type","string")}};putJsonArray("required"){add("action")}}; override suspend fun execute(a:Map<String,String>)=ToolResult(true,"Calendar ${a["action"]}")}
class AlarmTool : Tool { override val name="set_alarm"; override val description="Set alarm/reminder"; override val parameters=buildJsonObject{put("type","object");putJsonObject("properties"){putJsonObject("time"){put("type","string")};putJsonObject("label"){put("type","string")}};putJsonArray("required"){add("time")}}; override suspend fun execute(a:Map<String,String>)=ToolResult(true,"Alarm set")}
class NotesTool : Tool { override val name="save_note"; override val description="Save a note"; override val parameters=buildJsonObject{put("type","object");putJsonObject("properties"){putJsonObject("title"){put("type","string")};putJsonObject("content"){put("type","string")}};putJsonArray("required"){add("title");add("content")}}; override suspend fun execute(a:Map<String,String>)=ToolResult(true,"Note saved")}
class RememberTool : Tool { override val name="remember"; override val description="Remember something"; override val parameters=buildJsonObject{put("type","object");putJsonObject("properties"){putJsonObject("key"){put("type","string")};putJsonObject("value"){put("type","string")}};putJsonArray("required"){add("key");add("value")}}; override suspend fun execute(a:Map<String,String>)=ToolResult(true,"Remembered: ${a["key"]}")}
class RecallTool : Tool { override val name="recall"; override val description="Recall from memory"; override val parameters=buildJsonObject{put("type","object");putJsonObject("properties"){putJsonObject("query"){put("type","string")}};putJsonArray("required"){add("query")}}; override suspend fun execute(a:Map<String,String>)=ToolResult(true,"Recalled")}
class ProtocolTool : Tool { override val name="execute_protocol"; override val description="Execute workflow protocol"; override val parameters=buildJsonObject{put("type","object");putJsonObject("properties"){putJsonObject("protocolName"){put("type","string")}};putJsonArray("required"){add("protocolName")}}; override suspend fun execute(a:Map<String,String>)=ToolResult(true,"Protocol executed")}
class ScreenVisionTool : Tool { override val name="screen_vision"; override val description="AI screen analysis"; override val parameters=buildJsonObject{put("type","object");putJsonObject("properties"){putJsonObject("question"){put("type","string")}}}; override suspend fun execute(a:Map<String,String>)=ToolResult(true,"Screen analyzed")}
class CameraVisionTool : Tool { override val name="camera_vision"; override val description="AI camera analysis"; override val parameters=buildJsonObject{put("type","object");putJsonObject("properties"){putJsonObject("question"){put("type","string")}}}; override suspend fun execute(a:Map<String,String>)=ToolResult(true,"Camera analyzed")}
class BiometricTool : Tool { override val name="biometric_lock"; override val description="Enable/disable biometric lock"; override val parameters=buildJsonObject{put("type","object");putJsonObject("properties"){putJsonObject("action"){put("type","string");put("enum",JsonArray(listOf("enable","disable").map{JsonPrimitive(it)}))}};putJsonArray("required"){add("action")}}; override suspend fun execute(a:Map<String,String>)=ToolResult(true,"Biometric ${a["action"]}d")}
class ImageGenTool : Tool { override val name="generate_image"; override val description="Generate AI image"; override val parameters=buildJsonObject{put("type","object");putJsonObject("properties"){putJsonObject("prompt"){put("type","string")}};putJsonArray("required"){add("prompt")}}; override suspend fun execute(a:Map<String,String>)=ToolResult(true,"Image generated")}
class SelfDestructTool : Tool { override val name="self_destruct"; override val description="Clear all local data"; override val parameters=buildJsonObject{put("type","object");putJsonObject("properties"){putJsonObject("confirm"){put("type","string")}};putJsonArray("required"){add("confirm")}}; override suspend fun execute(a:Map<String,String>)=if(a["confirm"]?.uppercase()=="DELETE")ToolResult(true,"Data cleared")else ToolResult(false,"Type DELETE")}
class WidgetForgeTool : Tool { override val name="forge_widget"; override val description="Create floating widget"; override val parameters=buildJsonObject{put("type","object");putJsonObject("properties"){putJsonObject("type"){put("type","string");put("enum",JsonArray(listOf("timer","clock","stock").map{JsonPrimitive(it)}))}};putJsonArray("required"){add("type")}}; override suspend fun execute(a:Map<String,String>)=ToolResult(true,"Widget forged")}
